---
- hosts: elevate
  vars:
    project_path: /opt/backend/deployment
    root_path: /opt/
  tasks:
    - name: Slurp host file
      slurp:
        src: "{{ project_path }}/.token"
      register: slurpfile
    
    - name: Get vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}solution-upload-portal-service' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{ project_path }}/data2.json'"
      register: credentials
    - debug: msg="{{ credentials }}"

    - name: Set some variable
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
        current_path: "{{ project_path }}/solution-upload-portal-service"

    - name: Retrieve current release folder
      command: readlink -f solution-upload-portal-service
      register: current_release_path
      ignore_errors: yes
      args:
        chdir: "{{ project_path }}"

    - name: Create new folder
      file:
        dest: "{{ release_path }}"
        mode: 0755
        recurse: yes
        state: directory

    - name: Clone the Python repository
      git:
        repo: https://github.com/priyanka-TL/solution-upload-portal-service
        dest: "{{release_path}}"
        version: "{{gitBranch}}"
        force: yes

    - name: Install Python dependencies
      shell: |
        cd {{ release_path }}
        python3 -m venv venv
        bash -c "source venv/bin/activate && grep -v -E 'mkl-fft==|mkl-random==' requirements.txt > clean_requirements.txt && pip install -r clean_requirements.txt"

    - name: Generate .env
      shell: |
        cat {{ project_path }}/data2.json | {{ current_path }}/scripts/json2env.sh > {{ current_path }}/.env
      register: envConfig

    - name: Delete Old Folder
      shell: rm -rf {{ current_path }} && cd {{ project_path }} && mkdir solution-upload-portal-service

    - name: Move code
      shell: mv "{{ release_path }}"/* {{ current_path }}/

    - name: Set permission
      shell: chmod 744 {{ current_path }}/script/json2env.sh

    - name: Delete release folder
      shell: rm -rf {{ release_path }}

    - name: Start Python application
      command: "chdir={{current_path}} venv/bin/python app.py"
      register: pythonInfo